//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetail
    {
        public Nullable<int> MaBill { get; set; }
        public string proID { get; set; }
        public string proName { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> amount { get; set; }
        public int DetailID { get; set; }
    }
}
